# Generated by Django 2.2 on 2019-04-01 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rss',
            name='user_get',
            field=models.ManyToManyField(related_name='rss_get', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rss',
            name='user_read',
            field=models.ManyToManyField(related_name='rss_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
