# Generated by Django 2.2 on 2019-04-02 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190401_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rss',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='rss',
            name='user_get',
        ),
        migrations.RemoveField(
            model_name='rss',
            name='user_read',
        ),
        migrations.CreateModel(
            name='RssStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRead', models.BooleanField(default=False)),
                ('rss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Rss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_image', models.CharField(blank=True, max_length=128, null=True)),
                ('url_origin', models.CharField(max_length=128)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Channel')),
            ],
        ),
    ]
