# Generated by Django 2.2 on 2019-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_feed_url_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='url_origin',
            field=models.CharField(default='link', max_length=128),
            preserve_default=False,
        ),
    ]
