# Generated by Django 2.2 on 2019-04-02 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_feed_url_origin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rssstatus',
            unique_together={('user', 'rss')},
        ),
    ]
