# Generated by Django 2.2 on 2019-04-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190402_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
