# Generated by Django 2.2 on 2019-04-03 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20190403_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rss',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 14, 48, 8, 683511)),
        ),
        migrations.CreateModel(
            name='BlacklistChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
